
import { IPurchaseData, IPurchaseReceiptData, PurchaseLine } from "../models/purchase-model";

export const PURCHASE_FORM_DEFAULT: IPurchaseData = {
  id: 0,
  purchaseNumber: '',
  supplierNumber: 0,
  date: new Date(),
  printed: false,
  printedDate: null,
  freightCost: 0,
  notes: '',
  exportMyob: false,
  internalNotes: '',
  invoiceText: '',
  supplierId: 0,
  name: '',
  address: '',
  email: '',
  concatSupplierAddress: '',
  purchaseLines: [],
  dateCreated: new Date(),
  poNotes: '',
  isCourPlsReceivePays: false,
  isBesArrCollection: false,
  isCallReady: false,
  isCallReadyQuoting: false,
  isOthers: false,
  otherNotes: '',
  expanded: false,
  isApproved: false,
  supplierName: '',
  internal: false
}
export const PURCHASELINES_FORM_DEFAULT: PurchaseLine = {
  id: 0,
  purchaseLineNumber: 0,
  purchaseNumber: '',
  quantity: 0,
  quantityReceived: 0,
  received: false,
  description: '',
  dueDate: new Date(),
  costEach: 0,
  costTotal: 0,
  jobId: 0,
  accountNumber: '',
  isIncludeGST: false,
  isMaterialCertRequired: false,
  invoiceNumber: '',
  isEdit: false,
  isDeleted: false,
  refId: 0,
  purchaseReceipts: [],
  displayJobId: '',
  clientName: '',
  jobDescription: '',
  isCompleted: false,
  errorMessage: null,
  quantityDelivered: 0,
  gstAmount: 0,
  costEachTotal: 0
}


export const PURCHASELINESRECEIPT_FORM_DEFAULT: IPurchaseReceiptData = {
  id: 0,
  purchaseLineNumber: 0,
  date: null,
  poQuantity: 0,
  quantity: 0,
  packingSlipNumber: '',
  heatNumber: '',
  note: '',
  lotNumber: '',
  goodInspctReceivedBy: '',
  supplierName: '',
  purchaseNumber: 0,
  decription: '',
  jobId: 0,
  clientName: '',
  jobDescription: '',
  dataIndex: 0,
  historyReceipts: [],
  dueDate: null ,
  purchaseDate: null,
  created: null,
  displayJobId: '',
  quantityDelivered: 0,
  displayPurchaseNumber: '',
  quantityReceived: 0,
  quantityPreviouslyReceived: 0
}
